spring:
  profiles:
    include:
    - domain
    - common
  main:
    banner-mode: off
---
server:
  port: 8001
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
jwt:
  secret: asdsddladsldjaksjkdljklsjkldsaasdkjlasksadjkalsddjklksdalkdsajkl
  accessTokenExpire: 30
  refreshTokenExpire: 120
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
