api:
  uri: https://suwings.syu.ac.kr/websquare/engine/proworks/callServletService.jsp
expire: 10
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/doyoumate
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
