spring:
  profiles:
    include:
      - domain
      - common
      - env
  main:
    banner-mode: off
---
spring:
  config:
    activate:
      on-profile: local
jwt:
  secretKey: asdsddladsldjaksjkdljklsjkldsaasdkjlasksadjkalsddjklksdalkdsajkl
  accessTokenExpire: 30
  refreshTokenExpire: 120
---
spring:
  config:
    activate:
      on-profile: dev
jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
coolsms:
  apiKey: ${COOLSMS_API_KEY}
  secretKey: ${COOLSMS_SECRET_KEY}
  from: ${COOLSMS_FROM}
---
spring:
  config:
    activate:
      on-profile: prod
jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
coolsms:
  apiKey: ${COOLSMS_API_KEY}
  secretKey: ${COOLSMS_SECRET_KEY}
  from: ${COOLSMS_FROM}
