spring:
  profiles:
    include:
    - domain
    - common
    - env
  main:
    banner-mode: off
aws:
  credentials:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}
  cloudFront:
    domain: ${CLOUD_FRONT_DOMAIN}
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
coolsms:
  apiKey: ${COOLSMS_API_KEY}
  secretKey: ${COOLSMS_SECRET_KEY}
  from: ${COOLSMS_FROM}
