spring:
  profiles:
    include:
    - domain
    - common
    - env
  main:
    banner-mode: off
---
server:
  port: 8000
spring:
  config:
    activate:
      on-profile: local
jwt:
  secret: asdsddladsldjaksjkdljklsjkldsaasdkjlasksadjkalsddjklksdalkdsajkl
  accessTokenExpire: 1000000
  refreshTokenExpire: 1000000
---
spring:
  config:
    activate:
      on-profile: dev
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
coolsms:
  apiKey: ${COOLSMS_API_KEY}
  secretKey: ${COOLSMS_SECRET_KEY}
  from: ${COOLSMS_FROM}
---
spring:
  config:
    activate:
      on-profile: prod
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
coolsms:
  apiKey: ${COOLSMS_API_KEY}
  secretKey: ${COOLSMS_SECRET_KEY}
  from: ${COOLSMS_FROM}
