spring:
  profiles:
    include:
      - domain
      - common
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:batch
    username: sa
    password:
    driverClassName: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      name: ${JOB}
jwt:
  secretKey: asdsddladsldjaksjkdljklsjkldsaasdkjlasksadjkalsddjklksdalkdsajkl
  accessTokenExpire: 30
  refreshTokenExpire: 120
---
spring:
  config:
    activate:
      on-profile: dev
  batch:
    job:
      name: ${JOB}
jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
---
spring:
  config:
    activate:
      on-profile: prod
  batch:
    job:
      name: ${JOB}
jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
