spring:
  profiles:
    include:
      - domain
      - common
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:batch
    username: sa
    password:
    driverClassName: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
