spring:
  profiles:
    include:
    - domain
    - common
    - env
  main:
    banner-mode: off
    web-application-type: none
  datasource:
    url: jdbc:h2:mem:batch
    username: sa
    password:
    driverClassName: org.h2.Driver
  batch:
    job:
      name: ${JOB}
jwt:
  secret: ${JWT_SECRET}
  accessTokenExpire: ${JWT_ACCESS_EXPIRE}
  refreshTokenExpire: ${JWT_REFRESH_EXPIRE}
